-- =====================================================================
-- LRA Ops :: APPLY-TO-PRODUCTION.sql
--
-- Consolidated, ordered, ready-to-paste SQL for the Supabase SQL editor
-- (or a psql connection, if a connection string becomes available).
-- This is Phase 0 + Phase 1 in full: the rebuild plus the core/ops
-- schemas, RLS, and Chan's admin bootstrap.
--
-- ⚠️  THIS SCRIPT DROPS THE ENTIRE `public` SCHEMA, CASCADING.
--
-- Verified safe against the live project on 2026-09-08: a row census
-- found 47 rows total, every one seed data or derived from a single
-- employee record, zero transactional data. Full dump at
-- backup/pre-rebuild-snapshot.json (gitignored, contains PII) --
-- verified to exist and parse before this file was assembled. See
-- PLAN.md §0.1 for the table-by-table breakdown.
--
-- `auth`, `storage`, `graphql`, `extensions` and `realtime` are never
-- touched. Chan's one auth.users row (chanabayabay@gmail.com) survives
-- and is re-linked to a new core.users row with authority = 'admin' by
-- the final block below.
--
-- The coder agent does NOT run this against production. Chan applies
-- it — by pasting into the Supabase SQL editor, or by supplying a
-- connection string for `supabase db push` later. After it is applied
-- and `core`/`ops` are appended under Data API -> Exposed schemas,
-- `node scripts/verify-db.mjs` is the acceptance check.
--
-- Generated by concatenating supabase/migrations/*.sql in order.
-- The markers below show where each source migration begins.
-- =====================================================================

-- ---------------------------------------------------------------------
-- BEGIN migration: 20260908120000_000_drop_legacy_hr.sql
-- ---------------------------------------------------------------------

-- =====================================================================
-- LRA Ops :: 000 — the rebuild
--
-- Verified safe: a live row census on 2026-09-08 found 47 rows total,
-- every one seed data or derived from a single employee record, zero
-- transactional data (no payroll run, no leave request, no attendance
-- log, no audit row). Full dump at backup/pre-rebuild-snapshot.json
-- (gitignored, contains PII) -- verified to exist and parse before this
-- migration was written. PLAN.md §0.1 and §2.1.
--
-- This drops `public` ONLY. `auth`, `storage`, `graphql`, `extensions`
-- and `realtime` are never touched. Chan's one auth.users row
-- (chanabayabay@gmail.com) survives -- confirm in the Supabase dashboard
-- under Authentication immediately after this runs.
-- =====================================================================

drop schema public cascade;
create schema public;
grant usage on schema public to anon, authenticated, service_role;
comment on schema public is
  'Intentionally empty. LRA data lives in core and per-module schemas (ops, later hr/crm). '
  'public exists only because Postgres requires it and because extensions land near it.';

-- ---------------------------------------------------------------------
-- BEGIN migration: 20260908120100_core_identity.sql
-- ---------------------------------------------------------------------

-- =====================================================================
-- LRA Ops :: core — identity, authority, membership
--
-- Two ideas kept deliberately separate (PLAN.md §0.4 / PRD.md §2), because
-- conflating them is exactly what produced HR's "a manager can forge
-- hr_id" class of defect:
--
--   core.authority   -- company rank. staff / gm / founder / admin.
--                        Rarely changes. Multiple people can hold
--                        `founder` (Chan's father, and later his
--                        brothers), each their own row -- so authority
--                        lives on a plain column, not a hardcoded id.
--   core.memberships -- module participation + position. Additive.
--                        NOT an authority level. This is the seam that
--                        lets HR and CRM slot in later as `insert`, not
--                        `alter table`.
-- =====================================================================

create schema core;
grant usage on schema core to anon, authenticated, service_role;
comment on schema core is
  'Identity, authority, membership, notifications and audit history. '
  'The foundation HR and CRM will sit on. Owned by LRA-OpsSystem.';

create type core.authority as enum ('staff', 'gm', 'founder', 'admin');
create type core.module    as enum ('ops', 'hr', 'crm');
create type core.position  as enum
  ('founder', 'gm', 'sales', 'broker', 'hr_officer', 'accounting', 'other');

-- ---------------------------------------------------------------------
-- core.people — a human. May exist without a login (a new hire, someone
-- who has left). Deliberately thin: no salary, no government IDs, no
-- manager relation. Those are HR-module data and arrive as additive
-- columns in `hr` when HR is built (PLAN.md §0.3).
-- ---------------------------------------------------------------------
create table core.people (
  id           uuid primary key default gen_random_uuid(),
  person_code  text unique not null,          -- 'LRA-001'
  first_name   text not null,
  last_name    text not null,
  display_name text,                          -- short label for the board
  email        text unique not null,
  is_active    boolean not null default true,
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now()
);

-- ---------------------------------------------------------------------
-- core.users — a login. Mirrors auth.users. Authority is a plain column
-- so three founders can each hold their own account with no schema
-- change.
-- ---------------------------------------------------------------------
create table core.users (
  id         uuid primary key references auth.users(id) on delete cascade,
  email      text unique not null,
  authority  core.authority not null default 'staff',
  person_id  uuid unique references core.people(id) on delete set null,
  is_active  boolean not null default true,
  last_login timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index idx_core_users_authority on core.users(authority) where is_active;

-- ---------------------------------------------------------------------
-- core.memberships — participation in a module, in a position. NOT an
-- authority level. Position drives recurring-task templates and
-- scoreboard grouping.
-- ---------------------------------------------------------------------
create table core.memberships (
  id         uuid primary key default gen_random_uuid(),
  user_id    uuid not null references core.users(id) on delete cascade,
  module     core.module not null,
  position   core.position not null default 'other',
  is_active  boolean not null default true,
  joined_at  timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, module)
);
create index idx_core_memberships_module on core.memberships(module, position)
  where is_active;

-- ---------------------------------------------------------------------
-- Helper functions — the single source of authority. Modules call
-- these; modules never re-derive authority from a JWT. All
-- `security definer` so they can read core.users/core.memberships
-- regardless of the caller's own row-level visibility, and all
-- `set search_path` to close the classic search-path injection hole
-- that a SECURITY DEFINER function opens.
-- ---------------------------------------------------------------------

create or replace function core.auth_user_id()
returns uuid
language sql
stable
as $$
  select auth.uid();
$$;

-- Copied verbatim from LRA-HR migration 009, including the fix: absent
-- claims mean a direct connection (migration, psql, cron) and are
-- privileged; claims that EXIST but carry no `role` key are not. HR
-- shipped the naive version -- treating an empty role as privileged --
-- and one such token voided every guard in two migrations at once.
create or replace function core.is_system_caller()
returns boolean
language sql
stable
as $$
  select case
    -- No claims at all: a direct connection (migration, psql, cron).
    when nullif(current_setting('request.jwt.claims', true), '') is null
      then true
    -- Claims present: they must actually say service_role.
    else coalesce(
      nullif(current_setting('request.jwt.claims', true), '')::json ->> 'role',
      ''
    ) = 'service_role'
  end;
$$;

create or replace function core.authority()
returns core.authority
language sql
stable
security definer
set search_path = core, public
as $$
  select u.authority from core.users u where u.id = core.auth_user_id();
$$;

create or replace function core.is_admin()
returns boolean
language sql
stable
security definer
set search_path = core, public
as $$
  select coalesce(core.authority() = 'admin', false);
$$;

create or replace function core.is_founder()
returns boolean
language sql
stable
security definer
set search_path = core, public
as $$
  select coalesce(core.authority() in ('founder', 'admin'), false);
$$;

create or replace function core.is_gm()
returns boolean
language sql
stable
security definer
set search_path = core, public
as $$
  select coalesce(core.authority() in ('gm', 'admin'), false);
$$;

create or replace function core.is_oversight()
returns boolean
language sql
stable
security definer
set search_path = core, public
as $$
  select coalesce(core.authority() in ('gm', 'founder', 'admin'), false);
$$;

-- Admin counts as a member of every module for support purposes, same as
-- HR's COMPANY_WIDE_ROLES precedent -- but every other module capability
-- comes from an actual row, never an inference.
create or replace function core.is_member(p_module core.module)
returns boolean
language sql
stable
security definer
set search_path = core, public
as $$
  select core.is_admin() or exists (
    select 1 from core.memberships m
    where m.user_id = core.auth_user_id()
      and m.module = p_module
      and m.is_active
  );
$$;

-- ---------------------------------------------------------------------
-- Privilege-column guard on core.users. HR's migration 005 lesson,
-- written correctly the first time this round: only an admin may change
-- authority, person_id or is_active. Everything else (email sync,
-- last_login) is left open to the row owner and the system client.
-- ---------------------------------------------------------------------
create or replace function core.guard_user_privilege_columns()
returns trigger
language plpgsql
security definer
set search_path = core, public
as $$
begin
  if core.is_system_caller() or core.is_admin() then
    return new;
  end if;

  if new.authority is distinct from old.authority
     or new.person_id is distinct from old.person_id
     or new.is_active is distinct from old.is_active then
    raise exception 'authority, person_id and is_active may only be changed by an admin'
      using errcode = '42501';
  end if;

  return new;
end;
$$;

create trigger trg_guard_user_privilege_columns
  before update on core.users
  for each row execute function core.guard_user_privilege_columns();

-- updated_at maintenance, generic enough to reuse across schemas.
create or replace function core.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create trigger trg_core_people_updated_at
  before update on core.people
  for each row execute function core.set_updated_at();

create trigger trg_core_users_updated_at
  before update on core.users
  for each row execute function core.set_updated_at();

create trigger trg_core_memberships_updated_at
  before update on core.memberships
  for each row execute function core.set_updated_at();

-- ---------------------------------------------------------------------
-- BEGIN migration: 20260908120200_core_notifications_audit.sql
-- ---------------------------------------------------------------------

-- =====================================================================
-- LRA Ops :: core — notifications, outbox, audit
--
-- The forgeable-inbox defect is designed out here, not patched later.
-- HR shipped `create policy notifications_insert ... with check (true)`,
-- so any authenticated user could put a message, with a link, in
-- anyone's inbox. In an accountability system a spoofable "the founder
-- approved your points" is a product defect, not a nuisance. There is
-- therefore no INSERT policy for `authenticated` on core.notifications
-- at all in this migration or the RLS migration that follows it --
-- notifications originate only from the outbox drain, running on the
-- service client.
-- =====================================================================

create table core.notifications (
  id          uuid primary key default gen_random_uuid(),
  user_id     uuid not null references core.users(id) on delete cascade,
  title       text not null,
  message     text not null,
  entity_type text,          -- 'ops.task', 'ops.block', later 'quote'
  entity_id   uuid,
  link        text,
  is_read     boolean not null default false,
  created_at  timestamptz not null default now()
);
create index idx_core_notifications_user
  on core.notifications(user_id, is_read, created_at desc);

-- Only `is_read` may be changed by the row owner, and only their own
-- row. Enforced here by trigger; the RLS WITH CHECK re-states the
-- ownership half so the two layers agree.
create or replace function core.guard_notification_is_read_only()
returns trigger
language plpgsql
security definer
set search_path = core, public
as $$
begin
  if core.is_system_caller() or core.is_admin() then
    return new;
  end if;

  if new.user_id is distinct from old.user_id
     or new.title is distinct from old.title
     or new.message is distinct from old.message
     or new.entity_type is distinct from old.entity_type
     or new.entity_id is distinct from old.entity_id
     or new.link is distinct from old.link
     or new.created_at is distinct from old.created_at then
    raise exception 'only is_read may be changed on a notification'
      using errcode = '42501';
  end if;

  return new;
end;
$$;

create trigger trg_guard_notification_is_read_only
  before update on core.notifications
  for each row execute function core.guard_notification_is_read_only();

-- ---------------------------------------------------------------------
-- Outbox — delivery is abstracted from day one. In-app only in the MVP;
-- the drainer reads pending + in_app and inserts into core.notifications.
-- Email or WhatsApp later is a second drainer against this same table
-- with no call site touched.
-- ---------------------------------------------------------------------

create type core.outbox_channel as enum ('in_app', 'email', 'whatsapp');
create type core.outbox_state   as enum ('pending', 'sent', 'failed', 'skipped');

create table core.notification_outbox (
  id           uuid primary key default gen_random_uuid(),
  recipient_id uuid not null references core.users(id) on delete cascade,
  module       core.module not null,
  event_type   text not null,        -- 'ops.task.submitted', 'ops.block.opened'
  entity_type  text not null,
  entity_id    uuid,
  title        text not null,
  body         text not null,
  link         text,
  payload      jsonb not null default '{}'::jsonb,
  channel      core.outbox_channel not null default 'in_app',
  state        core.outbox_state not null default 'pending',
  attempts     int not null default 0,
  last_error   text,
  available_at timestamptz not null default now(),
  sent_at      timestamptz,
  created_at   timestamptz not null default now()
);
create index idx_core_outbox_pending
  on core.notification_outbox(channel, available_at) where state = 'pending';

-- ---------------------------------------------------------------------
-- Audit — append-only even to the service role. Not even the admin
-- account can rewrite history through any path.
-- ---------------------------------------------------------------------

create table core.audit_logs (
  id          uuid primary key default gen_random_uuid(),
  actor_id    uuid references core.users(id) on delete set null,
  actor_email text,
  actor_authority core.authority,
  module      core.module,
  action      text not null,
  entity_type text not null,     -- 'ops.task'; later 'quote', unprefixed on purpose
  entity_id   uuid,
  old_values  jsonb,
  new_values  jsonb,
  ip_address  inet,
  user_agent  text,
  created_at  timestamptz not null default now()
);
create index idx_core_audit_entity on core.audit_logs(entity_type, entity_id, created_at);
create index idx_core_audit_actor  on core.audit_logs(actor_id, created_at desc);

create or replace function core.forbid_audit_mutation()
returns trigger
language plpgsql
as $$
begin
  raise exception 'core.audit_logs is append-only; % is not permitted', tg_op
    using errcode = '42501';
end;
$$;

create trigger trg_forbid_audit_update
  before update on core.audit_logs
  for each row execute function core.forbid_audit_mutation();

create trigger trg_forbid_audit_delete
  before delete on core.audit_logs
  for each row execute function core.forbid_audit_mutation();

-- Read policy each module extends: the actor, or the entity owner, may
-- read a timeline row. Ops's branch (a task's owner may read its
-- timeline) is added in the ops RLS migration via `create or replace`.
-- Oversight always reads everything -- see the RLS migration.
create or replace function core.can_read_audit(p_entity_type text, p_entity_id uuid)
returns boolean
language sql
stable
security definer
set search_path = core, public
as $$
  select core.is_oversight();
$$;

-- ---------------------------------------------------------------------
-- BEGIN migration: 20260908120300_ops_foundation.sql
-- ---------------------------------------------------------------------

-- =====================================================================
-- LRA Ops :: ops — settings and weeks
--
-- The only module built now (PLAN.md §0.2). This migration lays the
-- foundation Phase 1 needs -- settings and the week calendar -- so the
-- API and web scaffold have something real to read. Catalog, tasks, the
-- state machine and the ledger are Phase 3/4 migrations; nothing here
-- pre-builds them.
-- =====================================================================

create schema ops;
grant usage on schema ops to anon, authenticated, service_role;
comment on schema ops is
  'The Ops module: weeks, task catalog, tasks, points ledger, blockers, scores. '
  'hr and crm are designed for, not created -- see PRD.md §0.3.';

create type ops.week_state as enum ('planning', 'open', 'closed');

create table ops.settings (
  id boolean primary key default true check (id),
  recurring_cap_pct           numeric(4,3) not null default 0.400
    check (recurring_cap_pct >= 0 and recurring_cap_pct < 1),
  recurring_floor_points      int not null default 3 check (recurring_floor_points >= 0),
  stale_after_days            int not null default 3 check (stale_after_days >= 1),
  reliability_window_weeks    int not null default 8,
  reliability_half_life_weeks numeric(4,2) not null default 3.0,
  min_weeks_for_rating        int not null default 3,
  leaderboard_visibility      text not null default 'all'
    check (leaderboard_visibility in ('all', 'oversight_only')),
  timezone   text not null default 'Asia/Manila',
  updated_by uuid references core.users(id),
  updated_at timestamptz not null default now()
);

-- Exactly one settings row. Seeded here, in the same migration, so the
-- table is never queried empty.
insert into ops.settings (id) values (true);

create trigger trg_ops_settings_updated_at
  before update on ops.settings
  for each row execute function core.set_updated_at();

-- Manila, always. Never UTC, never the browser's clock. A UTC-naive
-- implementation is wrong for 8 hours in every 24 -- Manila midnight is
-- 16:00 UTC the previous day.
create or replace function ops.week_start_for(p_ts timestamptz default now())
returns date
language sql
immutable
as $$
  select (date_trunc('week', (p_ts at time zone 'Asia/Manila')))::date;
$$;   -- date_trunc('week') is ISO: Monday.

create table ops.weeks (
  id uuid primary key default gen_random_uuid(),
  week_start date not null unique check (extract(isodow from week_start) = 1),
  week_end   date generated always as (week_start + 6) stored,
  state      ops.week_state not null default 'planning',
  briefing_opened_at timestamptz,
  briefing_closed_at timestamptz,
  briefing_closed_by uuid references core.users(id),
  closed_at timestamptz,
  closed_by uuid references core.users(id),
  rolled_over_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create trigger trg_ops_weeks_updated_at
  before update on ops.weeks
  for each row execute function core.set_updated_at();

-- ---------------------------------------------------------------------
-- BEGIN migration: 20260908120400_core_ops_rls.sql
-- ---------------------------------------------------------------------

-- =====================================================================
-- LRA Ops :: RLS and grants for core + ops (Phase 1 tables)
--
-- Every table in core and ops gets `enable row level security`. Every
-- UPDATE policy carries an explicit WITH CHECK -- Postgres silently
-- reuses USING as the check when it is omitted, which is how HR's
-- `users.role` became freely writable. A policy cannot express a state
-- machine; that arrives with the task triggers in Phase 3.
--
-- The revoke block at the bottom is the step that is easy to forget and
-- catastrophic to skip: Supabase grants ALL on new tables to
-- anon/authenticated and relies on RLS, but RLS does not apply to
-- TRUNCATE at all -- only the table grant stands in front of it, and
-- `truncate employees cascade` from the public anon key once emptied 23
-- HR tables with no login. `alter default privileges` is per schema, so
-- a fresh schema does NOT inherit another schema's revokes -- core and
-- ops each get their own full set here, and every future module schema
-- must repeat this block.
-- =====================================================================

-- ---------------------------------------------------------------------
-- 0. Baseline grants (mirrors what Supabase sets up automatically for
--    `public`; a schema we create ourselves does not inherit it).
-- ---------------------------------------------------------------------

grant select, insert, update, delete, truncate, trigger, references
  on all tables in schema core to anon, authenticated;
grant select, insert, update, delete, truncate, trigger, references
  on all tables in schema ops to anon, authenticated;
grant all on all tables in schema core to service_role;
grant all on all tables in schema ops to service_role;

alter default privileges in schema core
  grant select, insert, update, delete, truncate, trigger, references
  on tables to anon, authenticated;
alter default privileges in schema ops
  grant select, insert, update, delete, truncate, trigger, references
  on tables to anon, authenticated;
alter default privileges in schema core grant all on tables to service_role;
alter default privileges in schema ops  grant all on tables to service_role;

-- ---------------------------------------------------------------------
-- 1. Enable RLS everywhere.
-- ---------------------------------------------------------------------

alter table core.people enable row level security;
alter table core.users enable row level security;
alter table core.memberships enable row level security;
alter table core.notifications enable row level security;
alter table core.notification_outbox enable row level security;
alter table core.audit_logs enable row level security;
alter table ops.settings enable row level security;
alter table ops.weeks enable row level security;

-- ---------------------------------------------------------------------
-- 2. core.people — self, or oversight / admin write / admin write / none
-- ---------------------------------------------------------------------

create policy people_select on core.people for select to authenticated
using (
  core.is_oversight()
  or exists (
    select 1 from core.users u
    where u.id = core.auth_user_id() and u.person_id = core.people.id
  )
);

create policy people_insert on core.people for insert to authenticated
with check (core.is_admin());

create policy people_update on core.people for update to authenticated
using (core.is_admin())
with check (core.is_admin());

-- no DELETE policy: people are deactivated, never deleted.

-- ---------------------------------------------------------------------
-- 3. core.users — self or oversight / admin / self (guarded) + admin / none
-- ---------------------------------------------------------------------

create policy users_select on core.users for select to authenticated
using (id = core.auth_user_id() or core.is_oversight());

create policy users_insert on core.users for insert to authenticated
with check (core.is_admin());

-- The row owner may update their own row; an admin may update any row.
-- `trg_guard_user_privilege_columns` (core_identity.sql) is the real
-- enforcement of *which* columns a non-admin owner may touch.
create policy users_update on core.users for update to authenticated
using (id = core.auth_user_id() or core.is_admin())
with check (id = core.auth_user_id() or core.is_admin());

-- no DELETE policy: accounts are deactivated, never deleted.

-- ---------------------------------------------------------------------
-- 4. core.memberships — any active member reads / admin writes / none
-- ---------------------------------------------------------------------

create policy memberships_select on core.memberships for select to authenticated
using (
  core.is_admin()
  or (
    is_active
    and exists (
      select 1 from core.memberships caller
      where caller.user_id = core.auth_user_id() and caller.is_active
    )
  )
);

create policy memberships_insert on core.memberships for insert to authenticated
with check (core.is_admin());

create policy memberships_update on core.memberships for update to authenticated
using (core.is_admin())
with check (core.is_admin());

-- no DELETE policy: memberships are deactivated, never deleted.

-- ---------------------------------------------------------------------
-- 5. core.notifications — own inbox / NO insert for authenticated /
--    own row, is_read only (trigger-enforced) / own row delete
-- ---------------------------------------------------------------------

create policy notifications_select on core.notifications for select to authenticated
using (user_id = core.auth_user_id());

-- Deliberately no INSERT policy for `authenticated`. Notifications
-- originate only from the outbox drain, which runs on the service
-- client and therefore bypasses RLS entirely -- that is the point.

create policy notifications_update on core.notifications for update to authenticated
using (user_id = core.auth_user_id())
with check (user_id = core.auth_user_id());

create policy notifications_delete on core.notifications for delete to authenticated
using (user_id = core.auth_user_id());

-- ---------------------------------------------------------------------
-- 6. core.notification_outbox — recipient/oversight read / system-only write
-- ---------------------------------------------------------------------

create policy outbox_select on core.notification_outbox for select to authenticated
using (recipient_id = core.auth_user_id() or core.is_oversight());

-- No INSERT/UPDATE policy for `authenticated`: the outbox is written and
-- drained only by the service client.

-- ---------------------------------------------------------------------
-- 7. core.audit_logs — actor/entity-owner/oversight read / actor-stamped
--    insert / append-only (trigger already forbids UPDATE/DELETE outright)
-- ---------------------------------------------------------------------

create policy audit_select on core.audit_logs for select to authenticated
using (
  actor_id = core.auth_user_id()
  or core.can_read_audit(entity_type, entity_id)
);

create policy audit_insert on core.audit_logs for insert to authenticated
with check (actor_id = core.auth_user_id());

-- no UPDATE/DELETE policy, and the BEFORE triggers refuse both outright
-- with 42501 even for the table owner and the service role.

-- ---------------------------------------------------------------------
-- 8. ops.settings — ops member read / none insert / founder update / none
-- ---------------------------------------------------------------------

create policy settings_select on ops.settings for select to authenticated
using (core.is_member('ops'));

create policy settings_update on ops.settings for update to authenticated
using (core.is_founder())
with check (core.is_founder());

-- no INSERT/DELETE policy: exactly one settings row, seeded once.

-- ---------------------------------------------------------------------
-- 9. ops.weeks — ops member read / oversight insert / oversight update / none
-- ---------------------------------------------------------------------

create policy weeks_select on ops.weeks for select to authenticated
using (core.is_member('ops'));

create policy weeks_insert on ops.weeks for insert to authenticated
with check (core.is_oversight());

create policy weeks_update on ops.weeks for update to authenticated
using (core.is_oversight())
with check (core.is_oversight());

-- no DELETE policy: a week is closed, never deleted.

-- ---------------------------------------------------------------------
-- 10. The mandatory per-schema revoke block. RLS does not cover
--     TRUNCATE at all -- only this grant stands in front of it.
--     Every future module schema (hr, crm, ...) must repeat this block
--     in the same migration that creates it.
-- ---------------------------------------------------------------------

revoke truncate, trigger, references on all tables in schema core from anon, authenticated;
revoke truncate, trigger, references on all tables in schema ops  from anon, authenticated;
revoke delete on all tables in schema core from anon;
revoke delete on all tables in schema ops  from anon;
alter default privileges in schema core
  revoke truncate, trigger, references on tables from anon, authenticated;
alter default privileges in schema ops
  revoke truncate, trigger, references on tables from anon, authenticated;
alter default privileges in schema core revoke delete on tables from anon;
alter default privileges in schema ops  revoke delete on tables from anon;

-- ---------------------------------------------------------------------
-- BEGIN migration: 20260908120500_core_bootstrap_admin.sql
-- ---------------------------------------------------------------------

-- =====================================================================
-- LRA Ops :: bootstrap Chan's admin account
--
-- The rebuild (000_drop_legacy_hr) deliberately does not touch
-- `auth.users`, so Chan's one login survives the drop -- but `core.users`
-- is a brand-new, empty table. Without this migration nobody has a
-- `core.users` row at all, which means the auth middleware's profile
-- lookup fails for every caller including Chan, and the admin-only
-- provisioning route in Phase 2 (`requireAuthority('admin')`) can never
-- be reached by anyone. This migration exists to break that
-- chicken-and-egg: it links the one pre-existing `auth.users` row to a
-- `core.people` + `core.users` row with `authority = 'admin'`, keyed on
-- email so it works identically against the linked production project
-- (where the row exists) and a fresh local `supabase start` (where it
-- matches nothing and is a safe no-op).
--
-- Idempotent: safe to re-run, matches PLAN.md Phase 2's "re-running
-- finds the existing row and repairs what's missing" rule.
-- =====================================================================

do $$
declare
  v_auth_id uuid;
  v_person_id uuid;
begin
  select id into v_auth_id from auth.users where email = 'chanabayabay@gmail.com';

  if v_auth_id is null then
    -- Fresh local stack: no such auth user. Nothing to bootstrap.
    return;
  end if;

  insert into core.people (person_code, first_name, last_name, display_name, email)
  values ('LRA-001', 'Chan', 'Abay-abay', 'Chan', 'chanabayabay@gmail.com')
  on conflict (email) do nothing
  returning id into v_person_id;

  if v_person_id is null then
    select id into v_person_id from core.people where email = 'chanabayabay@gmail.com';
  end if;

  insert into core.users (id, email, authority, person_id)
  values (v_auth_id, 'chanabayabay@gmail.com', 'admin', v_person_id)
  on conflict (id) do update
    set person_id = excluded.person_id
    where core.users.person_id is null;

  insert into core.memberships (user_id, module, position)
  values (v_auth_id, 'ops', 'other')
  on conflict (user_id, module) do nothing;
end $$;

