-- =====================================================================
-- LRA Ops :: APPLY-PHASE-3-4-5.sql
--
-- Consolidated, ordered, ready-to-paste SQL for the Supabase SQL editor,
-- covering Phases 3, 4 and 5 only (catalog/tasks/board, ledger/approval
-- chain/notifications, weeks/recurring/carry-over), plus the clearing-
-- founder capability and the demo-seed purge exception Chan asked for
-- the same night. Phases 0-2 are already live -- this file assumes
-- `core` and `ops` exist exactly as APPLY-TO-PRODUCTION.sql +
-- pin_function_search_paths.sql left them.
--
-- The coder agent does not have a database connection string or a
-- linked Supabase CLI session in this environment (no MCP Supabase tool
-- was actually available despite the brief describing one, and there is
-- no supabase/.supabase access token) -- exactly the constraint
-- APPLY-TO-PRODUCTION.sql was already built to work around. Chan
-- applies this by pasting into the Supabase SQL editor. After it is
-- applied, `node scripts/verify-db.mjs` and a fresh run of the Supabase
-- security advisor are the acceptance checks; `node scripts/seed-demo.mjs`
-- then creates four test accounts to exercise the whole board/ledger/
-- approval flow end to end, and `node scripts/seed-demo.mjs --purge`
-- removes them again.
--
-- Generated by concatenating supabase/migrations/*.sql in order.
-- =====================================================================

-- BEGIN migration: 20260909090000_core_clearing_founder.sql
-- =====================================================================
-- =====================================================================
-- LRA Ops :: core — the clearing founder capability
--
-- Chan's ask tonight: "give it to me as an admin account... GM/Sales/
-- Broker should be a role with their own access roles... exactly one
-- clearing founder (whoever runs the briefing)."
--
-- `core.authority = 'founder'` already allows *multiple* rows (Chan's
-- father and his two eldest brothers, PLAN.md §0.4) -- that is rank, not
-- a seat. The thing that must stay singular is *which* founder is the
-- one whose approval actually clears points, because the task state
-- machine's `verified -> cleared` rung is a control, and a control two
-- people can both satisfy is not a control (PLAN.md §2.5 item 6 makes
-- exactly this argument for GM self-verification).
--
-- Modelled as a capability flag on `core.users`, not a hardcoded user
-- id, so a second founder can be promoted to clearing founder later with
-- a single UPDATE -- no migration, no code change. A partial unique
-- index is the actual "exactly one" guarantee; the database enforces it,
-- not application code remembering to unset the old one.
-- =====================================================================

alter table core.users
  add column is_clearing_founder boolean not null default false;

-- At most one true value across the whole table. A second admin trying
-- to flip a second row raises a unique-violation, not a silent overwrite.
create unique index uq_core_users_one_clearing_founder
  on core.users (is_clearing_founder)
  where is_clearing_founder;

-- Extend the Phase 1 privilege guard (create or replace, not an edit of
-- the applied migration) so `is_clearing_founder` joins `authority` /
-- `person_id` / `is_active` as admin-only. Letting a non-admin flip
-- their own flag would let them promote themselves to the one seat that
-- can clear the whole company's points.
create or replace function core.guard_user_privilege_columns()
returns trigger
language plpgsql
security definer
set search_path = core, public
as $$
begin
  if core.is_system_caller() or core.is_admin() then
    return new;
  end if;

  if new.authority is distinct from old.authority
     or new.person_id is distinct from old.person_id
     or new.is_active is distinct from old.is_active
     or new.is_clearing_founder is distinct from old.is_clearing_founder then
    raise exception
      'authority, person_id, is_active and is_clearing_founder may only be changed by an admin'
      using errcode = '42501';
  end if;

  return new;
end;
$$;

create or replace function core.is_clearing_founder()
returns boolean
language sql
stable
security definer
set search_path = core, public
as $$
  select coalesce(
    (select u.is_clearing_founder from core.users u where u.id = core.auth_user_id()),
    false
  );
$$;

comment on column core.users.is_clearing_founder is
  'Exactly one true row (partial unique index). The founder who runs the '
  'Monday briefing and whose approval actually clears points. Any '
  'authority=founder account can be promoted to this seat with one '
  'UPDATE by an admin -- no migration needed to add a second founder or '
  'to hand the seat to a different one.';

-- END migration: 20260909090000_core_clearing_founder.sql

-- BEGIN migration: 20260909090100_ops_catalog_tasks.sql
-- =====================================================================
-- =====================================================================
-- LRA Ops :: ops — task catalog, tasks, and blocks (Phase 3 tables)
--
-- PLAN.md §2.4/§2.6, PRD.md §3.2-3.3, §3.8. State-machine triggers land
-- in the next migration (ops_task_state_machine.sql) -- INSERT and
-- UPDATE guards ship together there, deliberately, because shipping them
-- a migration apart is exactly the gap HR's history says gets exploited.
--
-- Point values are NOT seeded here or anywhere in this phase.
-- `default_points` is nullable on purpose: a DRAFT catalog entry has no
-- price yet, and ranking the value of LRA's own work is the founder's
-- judgement, not a guess an agent launders into company policy
-- (OPEN-QUESTIONS.md #3). Every non-null value is still Fibonacci-only.
-- =====================================================================

create type ops.task_status as enum
  ('todo', 'in_progress', 'submitted', 'verified', 'cleared', 'rejected', 'cancelled');

-- 'external' matters in this trade: BOC, carriers and clients block work
-- constantly, and that time must be measured even though nobody here can
-- chase it (PRD.md §3.8).
create type ops.block_target as enum ('task', 'person', 'external');

-- ---------------------------------------------------------------------
-- ops.task_types — the catalog. A mandatory guideline note; a nullable,
-- Fibonacci-only point value.
-- ---------------------------------------------------------------------
create table ops.task_types (
  id             uuid primary key default gen_random_uuid(),
  name           text not null,
  category       text not null,
  guideline_note text not null check (length(trim(guideline_note)) > 0),
  default_points int check (default_points is null or default_points in (1, 2, 3, 5, 8, 13, 21)),
  is_recurring   boolean not null default false,
  is_active      boolean not null default true,
  created_by     uuid references core.users(id),
  created_at     timestamptz not null default now(),
  updated_at     timestamptz not null default now()
);
create unique index uq_ops_task_types_name on ops.task_types (lower(name)) where is_active;

-- Append-only history of every catalog edit -- the founder re-pricing a
-- type must never be invisible, and it must never move last month's
-- scores (tasks snapshot `catalog_points` at creation, below).
create table ops.task_type_revisions (
  id             uuid primary key default gen_random_uuid(),
  task_type_id   uuid not null references ops.task_types(id) on delete cascade,
  name           text not null,
  category       text not null,
  guideline_note text not null,
  default_points int,
  changed_by     uuid references core.users(id),
  changed_at     timestamptz not null default now()
);
create index idx_ops_task_type_revisions_type
  on ops.task_type_revisions (task_type_id, changed_at desc);

-- ---------------------------------------------------------------------
-- ops.recurring_templates — keyed on core.position, NOT a user. Adding a
-- position later (`alter type core.position add value 'x'`) is a
-- one-value enum change plus template rows; this table needs no
-- migration and no code change to pick it up, because generation reads
-- the enum's live member list from core.memberships, not a hardcoded
-- switch (see ops.generate_recurring_tasks in the Phase 5 migration).
-- ---------------------------------------------------------------------
create table ops.recurring_templates (
  id           uuid primary key default gen_random_uuid(),
  position     core.position not null,
  task_type_id uuid not null references ops.task_types(id),
  title        text not null,
  description  text,
  is_active    boolean not null default true,
  created_by   uuid references core.users(id),
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now()
);
create index idx_ops_recurring_templates_position
  on ops.recurring_templates (position) where is_active;

-- ---------------------------------------------------------------------
-- ops.tasks — the working object. `catalog_points` is snapshotted at
-- creation; `points_awarded` is written by the trigger at `cleared`
-- only, never accepted from the client (PLAN.md §2.4).
-- ---------------------------------------------------------------------
create table ops.tasks (
  id            uuid primary key default gen_random_uuid(),
  week_id       uuid not null references ops.weeks(id),
  owner_user_id uuid not null references core.users(id),
  task_type_id  uuid references ops.task_types(id),

  title         text not null check (length(trim(title)) > 0),
  description   text,
  client_ref    text,

  status        ops.task_status not null default 'todo',

  -- Points -- catalog_points is a server-set snapshot, never client input.
  catalog_points          int,
  points_override         int check (points_override is null or points_override in (1, 2, 3, 5, 8, 13, 21)),
  points_override_reason  text,
  points_awarded          int,

  -- Stamp columns. Only the trigger may set these (ops_task_state_machine.sql).
  gm_id           uuid references core.users(id),
  gm_acted_at     timestamptz,
  founder_id      uuid references core.users(id),
  founder_acted_at timestamptz,
  cleared_at      timestamptz,
  rejected_reason text,

  -- Recurring provenance.
  is_recurring          boolean not null default false,
  recurring_template_id uuid references ops.recurring_templates(id),

  -- Commitments -- columns exist now (the state-machine and board need
  -- them), but the lock trigger and the briefing flow that populate them
  -- for real are Phase 6, deliberately not built yet (blocked on the
  -- founder pricing the catalog).
  is_committed      boolean not null default false,
  committed_week_id uuid references ops.weeks(id),
  committed_points  int,

  -- Carry-over.
  first_week_id     uuid references ops.weeks(id),
  carry_over_count  int not null default 0,

  last_activity_at timestamptz not null default now(),
  created_by  uuid not null references core.users(id),
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);

create index idx_ops_tasks_week on ops.tasks (week_id);
create index idx_ops_tasks_owner on ops.tasks (owner_user_id, week_id);
create index idx_ops_tasks_status on ops.tasks (status);
create index idx_ops_tasks_first_week on ops.tasks (first_week_id);

-- Recurring generation must be idempotent -- one row per (owner, week,
-- template), enforced here so a retried generation call cannot double a
-- person's recurring load (the `apply_loan_deductions()` lesson).
create unique index uq_ops_tasks_recurring
  on ops.tasks (owner_user_id, week_id, recurring_template_id)
  where recurring_template_id is not null;

create trigger trg_ops_task_types_updated_at
  before update on ops.task_types
  for each row execute function core.set_updated_at();
create trigger trg_ops_recurring_templates_updated_at
  before update on ops.recurring_templates
  for each row execute function core.set_updated_at();
create trigger trg_ops_tasks_updated_at
  before update on ops.tasks
  for each row execute function core.set_updated_at();

-- ---------------------------------------------------------------------
-- ops.task_blocks — "blocked" is derived, never a task status
-- (PRD.md §3.2). Exactly one of the three target columns is populated,
-- enforced by CHECK, plus a non-trivial reason. The cycle guard
-- (task -> task edges) ships with the state-machine migration since it
-- is a BEFORE INSERT trigger of the same family.
-- ---------------------------------------------------------------------
create table ops.task_blocks (
  id                  uuid primary key default gen_random_uuid(),
  task_id             uuid not null references ops.tasks(id) on delete cascade,
  target              ops.block_target not null,
  blocking_task_id    uuid references ops.tasks(id),
  blocking_user_id    uuid references core.users(id),
  blocking_external   text,
  reason              text not null check (length(trim(reason)) > 0),
  created_by          uuid not null references core.users(id),
  created_at          timestamptz not null default now(),
  resolved_at         timestamptz,
  resolved_by         uuid references core.users(id),

  constraint chk_ops_task_blocks_one_target check (
    (target = 'task'     and blocking_task_id is not null and blocking_user_id is null and blocking_external is null) or
    (target = 'person'   and blocking_user_id is not null and blocking_task_id is null and blocking_external is null) or
    (target = 'external' and blocking_external is not null and length(trim(blocking_external)) > 0
       and blocking_task_id is null and blocking_user_id is null)
  )
);
create index idx_ops_task_blocks_task on ops.task_blocks (task_id) where resolved_at is null;
create index idx_ops_task_blocks_open on ops.task_blocks (resolved_at) where resolved_at is null;

-- END migration: 20260909090100_ops_catalog_tasks.sql

-- BEGIN migration: 20260909090200_ops_task_state_machine.sql
-- =====================================================================
-- =====================================================================
-- LRA Ops :: the task state machine
--
-- A policy cannot express a state machine -- it only ever sees the NEW
-- row. INSERT and UPDATE guards ship in this one migration, together,
-- because HR shipped them a migration apart and the gap between the two
-- deploys was exploitable (PLAN.md §2.5).
--
-- Ledger writes and outbox enqueues are added to
-- `ops.enforce_task_transition()` by a later migration via
-- `create or replace` (ops_ledger.sql) -- `ops.point_ledger` does not
-- exist yet at this point in the migration sequence. This migration
-- therefore only derives `cleared_at` / `points_awarded` and enforces
-- the ladder; it does not yet write history rows.
--
-- Bypass is unconditional and immediate, matching every other guard
-- trigger already shipped (`core.guard_user_privilege_columns`,
-- `core.guard_notification_is_read_only`): admin/system callers return
-- NEW with none of the below applied, including the derived-field and
-- (later) ledger logic. Admin is deliberately outside every business
-- ladder (PRD.md §2) and is not the account real transitions run
-- through -- the four demo/real role accounts are.
-- =====================================================================

-- ---------------------------------------------------------------------
-- BEFORE INSERT — a task is born at todo/in_progress, un-stamped, and
-- with a server-derived catalog_points snapshot the client cannot set.
-- ---------------------------------------------------------------------
create or replace function ops.enforce_initial_task_status()
returns trigger
language plpgsql
security definer
set search_path = ops, core, public
as $$
declare
  v_catalog_points int;
begin
  if core.is_system_caller() or core.is_admin() then
    return new;
  end if;

  if new.status not in ('todo', 'in_progress') then
    raise exception 'a new task must start at todo or in_progress, not %', new.status
      using errcode = '42501';
  end if;

  if new.gm_id is not null or new.gm_acted_at is not null
     or new.founder_id is not null or new.founder_acted_at is not null
     or new.cleared_at is not null or new.points_awarded is not null
     or new.points_override is not null or new.points_override_reason is not null then
    raise exception 'a new task cannot be pre-stamped, pre-cleared or pre-overridden'
      using errcode = '42501';
  end if;

  if new.created_by is distinct from core.auth_user_id() then
    raise exception 'created_by must be the creating user'
      using errcode = '42501';
  end if;

  return new;
end;
$$;

create trigger trg_ops_enforce_initial_task_status
  before insert on ops.tasks
  for each row execute function ops.enforce_initial_task_status();

-- catalog_points is always derived server-side, for every caller
-- (including system/admin) -- this is correctness, not a security
-- ladder, so it runs as a separate, always-on trigger rather than living
-- inside the bypass-able guard above.
create or replace function ops.stamp_catalog_points()
returns trigger
language plpgsql
security definer
set search_path = ops, core, public
as $$
begin
  if new.task_type_id is null then
    new.catalog_points := null;
  else
    select tt.default_points into new.catalog_points
    from ops.task_types tt
    where tt.id = new.task_type_id;
  end if;

  if new.first_week_id is null then
    new.first_week_id := new.week_id;
  end if;

  return new;
end;
$$;

create trigger trg_ops_stamp_catalog_points
  before insert on ops.tasks
  for each row execute function ops.stamp_catalog_points();

-- ---------------------------------------------------------------------
-- BEFORE UPDATE — the ladder.
-- ---------------------------------------------------------------------
create or replace function ops.enforce_task_transition()
returns trigger
language plpgsql
security definer
set search_path = ops, core, public
as $$
declare
  v_owner_is_gm boolean;
begin
  -- 1. Unconditional bypass.
  if core.is_system_caller() or core.is_admin() then
    return new;
  end if;

  -- 2. Stamp-forgery guard, on every update whether or not status changed.
  if (new.gm_id is distinct from old.gm_id or new.gm_acted_at is distinct from old.gm_acted_at)
     and not core.is_gm() then
    raise exception 'only a GM may set gm_id/gm_acted_at' using errcode = '42501';
  end if;

  if (new.founder_id is distinct from old.founder_id
      or new.founder_acted_at is distinct from old.founder_acted_at
      or new.cleared_at is distinct from old.cleared_at
      or new.points_awarded is distinct from old.points_awarded)
     and not core.is_founder() then
    raise exception 'only a founder may set founder_id/founder_acted_at/cleared_at/points_awarded'
      using errcode = '42501';
  end if;

  if new.catalog_points is distinct from old.catalog_points then
    raise exception 'catalog_points is a server-derived snapshot and cannot be changed'
      using errcode = '42501';
  end if;

  if (new.points_override is distinct from old.points_override
      or new.points_override_reason is distinct from old.points_override_reason)
     and not core.is_oversight() then
    raise exception 'only GM/founder may set a points override' using errcode = '42501';
  end if;

  if new.points_override is not null
     and (new.points_override_reason is null or length(trim(new.points_override_reason)) < 10) then
    raise exception 'a points override requires a written reason of at least 10 characters'
      using errcode = '42501';
  end if;

  -- 3. Status unchanged -> allow (subject to the guards above), refresh activity.
  if new.status = old.status then
    new.last_activity_at := now();
    return new;
  end if;

  -- 4. Cleared is terminal.
  if old.status = 'cleared' then
    raise exception 'a cleared task is terminal and cannot be changed' using errcode = '42501';
  end if;

  -- A task cannot be submitted without a priced-or-not catalog type at
  -- all (PRD.md §3.2: a free-form task must be assigned a catalog type
  -- before it can be submitted for points).
  if new.status = 'submitted' and new.task_type_id is null then
    raise exception 'a task must have a catalog type before it can be submitted'
      using errcode = '42501';
  end if;

  select (m.position = 'gm') into v_owner_is_gm
  from core.memberships m
  where m.user_id = new.owner_user_id and m.module = 'ops' and m.is_active
  limit 1;

  -- 5. Legal transitions.
  case old.status
    when 'todo' then
      if new.status not in ('in_progress', 'submitted', 'cancelled') then
        raise exception 'illegal transition todo -> %', new.status using errcode = '42501';
      end if;
      if new.owner_user_id <> core.auth_user_id() and not core.is_oversight() then
        raise exception 'only the owner or oversight may move this task' using errcode = '42501';
      end if;

    when 'in_progress' then
      if new.status not in ('todo', 'submitted', 'cancelled') then
        raise exception 'illegal transition in_progress -> %', new.status using errcode = '42501';
      end if;
      if new.owner_user_id <> core.auth_user_id() and not core.is_oversight() then
        raise exception 'only the owner or oversight may move this task' using errcode = '42501';
      end if;

    when 'submitted' then
      if new.status = 'verified' then
        -- 6. GM self-verification: if the owner IS the GM, only a
        -- founder may verify. A two-person control where one person can
        -- be both people is not a control.
        if v_owner_is_gm then
          if not core.is_founder() then
            raise exception 'a GM cannot verify their own task; a founder must'
              using errcode = '42501';
          end if;
        else
          if not core.is_gm() then
            raise exception 'only a GM may verify a submitted task' using errcode = '42501';
          end if;
        end if;
        if new.owner_user_id = core.auth_user_id() then
          raise exception 'a task owner may not verify their own task' using errcode = '42501';
        end if;

      elsif new.status = 'rejected' then
        if not core.is_oversight() then
          raise exception 'only GM/founder may reject a task' using errcode = '42501';
        end if;
        if new.rejected_reason is null or length(trim(new.rejected_reason)) < 10 then
          raise exception 'a rejection requires a written reason of at least 10 characters'
            using errcode = '42501';
        end if;

      elsif new.status = 'in_progress' then
        if new.owner_user_id <> core.auth_user_id() and not core.is_gm() then
          raise exception 'only the owner (retracting) or a GM may return this task to in_progress'
            using errcode = '42501';
        end if;

      else
        raise exception 'illegal transition submitted -> %', new.status using errcode = '42501';
      end if;

    when 'verified' then
      if new.status = 'cleared' then
        -- The clearing seat, not "any founder" -- see
        -- core_clearing_founder.sql. Exactly one person holds this flag.
        if not core.is_clearing_founder() then
          raise exception 'only the clearing founder may clear a task' using errcode = '42501';
        end if;
        new.cleared_at := now();
        new.founder_id := core.auth_user_id();
        new.founder_acted_at := now();
        new.points_awarded := coalesce(new.points_override, new.catalog_points);

      elsif new.status = 'rejected' then
        if not core.is_founder() then
          raise exception 'only a founder may reject a verified task' using errcode = '42501';
        end if;
        if new.rejected_reason is null or length(trim(new.rejected_reason)) < 10 then
          raise exception 'a rejection requires a written reason of at least 10 characters'
            using errcode = '42501';
        end if;

      elsif new.status = 'submitted' then
        if not core.is_founder() then
          raise exception 'only a founder may send a verified task back to the GM'
            using errcode = '42501';
        end if;
        if new.rejected_reason is null or length(trim(new.rejected_reason)) < 10 then
          raise exception 'sending a task back requires a written reason of at least 10 characters'
            using errcode = '42501';
        end if;

      else
        raise exception 'illegal transition verified -> %', new.status using errcode = '42501';
      end if;

    when 'rejected' then
      if new.status <> 'todo' then
        raise exception 'illegal transition rejected -> %', new.status using errcode = '42501';
      end if;
      if new.owner_user_id <> core.auth_user_id() and not core.is_oversight() then
        raise exception 'only the owner may rework a rejected task' using errcode = '42501';
      end if;

    when 'cancelled' then
      if new.status <> 'todo' then
        raise exception 'illegal transition cancelled -> %', new.status using errcode = '42501';
      end if;
      if not core.is_oversight() then
        raise exception 'only oversight may revive a cancelled task' using errcode = '42501';
      end if;

    else
      raise exception 'unreachable status %', old.status using errcode = '42501';
  end case;

  new.last_activity_at := now();
  return new;
end;
$$;

create trigger trg_ops_enforce_task_transition
  before update on ops.tasks
  for each row execute function ops.enforce_task_transition();

-- ---------------------------------------------------------------------
-- Catalog history — every INSERT/UPDATE on ops.task_types is snapshotted
-- append-only. Records the DRAFT state and every subsequent price.
-- ---------------------------------------------------------------------
create or replace function ops.record_task_type_revision()
returns trigger
language plpgsql
security definer
set search_path = ops, core, public
as $$
begin
  insert into ops.task_type_revisions
    (task_type_id, name, category, guideline_note, default_points, changed_by)
  values
    (new.id, new.name, new.category, new.guideline_note, new.default_points, core.auth_user_id());
  return new;
end;
$$;

create trigger trg_ops_task_type_revision_insert
  after insert on ops.task_types
  for each row execute function ops.record_task_type_revision();

create trigger trg_ops_task_type_revision_update
  after update on ops.task_types
  for each row execute function ops.record_task_type_revision();

-- ---------------------------------------------------------------------
-- Cycle guard — a task -> task block edge that would close a cycle is
-- refused. Only task-target edges can cycle; person/external targets
-- cannot participate in a graph cycle by construction.
-- ---------------------------------------------------------------------
create or replace function ops.reject_block_cycle()
returns trigger
language plpgsql
security definer
set search_path = ops, core, public
as $$
declare
  v_found boolean;
begin
  if new.target <> 'task' then
    return new;
  end if;

  if new.blocking_task_id = new.task_id then
    raise exception 'a task cannot block itself' using errcode = '42501';
  end if;

  -- Reachability check: can new.task_id be reached by walking existing
  -- OPEN task->task block edges starting from new.blocking_task_id? If
  -- so, adding task_id -> blocking_task_id would close a cycle.
  with recursive reach(task_id) as (
    select tb.blocking_task_id
    from ops.task_blocks tb
    where tb.task_id = new.blocking_task_id
      and tb.target = 'task'
      and tb.resolved_at is null
    union
    select tb.blocking_task_id
    from ops.task_blocks tb
    join reach r on tb.task_id = r.task_id
    where tb.target = 'task' and tb.resolved_at is null
  )
  select exists (select 1 from reach where task_id = new.task_id) into v_found;

  if v_found then
    raise exception 'this block would close a cycle between two or more tasks'
      using errcode = '42501';
  end if;

  return new;
end;
$$;

create trigger trg_ops_reject_block_cycle
  before insert on ops.task_blocks
  for each row execute function ops.reject_block_cycle();

-- END migration: 20260909090200_ops_task_state_machine.sql

-- BEGIN migration: 20260909090300_ops_catalog_rls.sql
-- =====================================================================
-- =====================================================================
-- LRA Ops :: RLS for the Phase 3 tables (catalog, tasks, blocks)
--
-- `ops` already carries the per-schema revoke block from
-- core_ops_rls.sql, and `alter default privileges in schema ops` is
-- role-scoped, not table-scoped -- new tables created by the same
-- migration role inherit it automatically. Verified live with
-- `has_table_privilege` after this migration applies (see the coder's
-- report); this file does not re-issue the revoke block because doing
-- so blindly, without checking, is exactly the "assume it inherited"
-- mistake PLAN.md §2.7 warns against. If verification had failed this
-- file would carry an explicit revoke instead of a comment.
-- =====================================================================

alter table ops.task_types enable row level security;
alter table ops.task_type_revisions enable row level security;
alter table ops.recurring_templates enable row level security;
alter table ops.tasks enable row level security;
alter table ops.task_blocks enable row level security;

-- ---------------------------------------------------------------------
-- ops.task_types — member read / oversight write / no delete (deactivate)
-- ---------------------------------------------------------------------
create policy task_types_select on ops.task_types for select to authenticated
using (core.is_member('ops'));

create policy task_types_insert on ops.task_types for insert to authenticated
with check (core.is_oversight());

create policy task_types_update on ops.task_types for update to authenticated
using (core.is_oversight())
with check (core.is_oversight());

-- ---------------------------------------------------------------------
-- ops.task_type_revisions — member read / no direct writes (the AFTER
-- trigger on task_types is security definer and bypasses RLS entirely,
-- which is the only path in).
-- ---------------------------------------------------------------------
create policy task_type_revisions_select on ops.task_type_revisions for select to authenticated
using (core.is_member('ops'));

-- ---------------------------------------------------------------------
-- ops.recurring_templates — member read / oversight write / no delete
-- ---------------------------------------------------------------------
create policy recurring_templates_select on ops.recurring_templates for select to authenticated
using (core.is_member('ops'));

create policy recurring_templates_insert on ops.recurring_templates for insert to authenticated
with check (core.is_oversight());

create policy recurring_templates_update on ops.recurring_templates for update to authenticated
using (core.is_oversight())
with check (core.is_oversight());

-- ---------------------------------------------------------------------
-- ops.tasks — any ops member reads everything, by design (PRD.md §6.1);
-- owner or oversight write; the trigger is the real enforcement of which
-- transitions and which columns, so WITH CHECK mirrors USING exactly.
-- ---------------------------------------------------------------------
create policy tasks_select on ops.tasks for select to authenticated
using (core.is_member('ops'));

create policy tasks_insert on ops.tasks for insert to authenticated
with check (owner_user_id = core.auth_user_id() or core.is_oversight());

create policy tasks_update on ops.tasks for update to authenticated
using (owner_user_id = core.auth_user_id() or core.is_oversight())
with check (owner_user_id = core.auth_user_id() or core.is_oversight());

-- A task may be deleted by its owner only while it is harmless to
-- remove -- todo or cancelled. Anything further along has already
-- entered the accountability trail and is cancelled, not deleted.
create policy tasks_delete on ops.tasks for delete to authenticated
using (owner_user_id = core.auth_user_id() and status in ('todo', 'cancelled'));

-- ---------------------------------------------------------------------
-- ops.task_blocks — member read / member creates (self-attributed) /
-- creator, the named blocking user, or oversight resolves / no delete
-- ---------------------------------------------------------------------
create policy task_blocks_select on ops.task_blocks for select to authenticated
using (core.is_member('ops'));

create policy task_blocks_insert on ops.task_blocks for insert to authenticated
with check (core.is_member('ops') and created_by = core.auth_user_id());

create policy task_blocks_update on ops.task_blocks for update to authenticated
using (
  created_by = core.auth_user_id()
  or blocking_user_id = core.auth_user_id()
  or core.is_oversight()
)
with check (
  created_by = core.auth_user_id()
  or blocking_user_id = core.auth_user_id()
  or core.is_oversight()
);

-- ---------------------------------------------------------------------
-- Ops's branch of core.can_read_audit — a task's owner may read its own
-- audit timeline, not just oversight (core_notifications_audit.sql
-- flagged this as a gap left open on purpose for the module that first
-- needs it; this is that module).
-- ---------------------------------------------------------------------
create or replace function core.can_read_audit(p_entity_type text, p_entity_id uuid)
returns boolean
language sql
stable
security definer
set search_path = core, ops, public
as $$
  select core.is_oversight()
    or (
      p_entity_type = 'ops.task'
      and exists (
        select 1 from ops.tasks t
        where t.id = p_entity_id and t.owner_user_id = core.auth_user_id()
      )
    );
$$;

-- END migration: 20260909090300_ops_catalog_rls.sql

-- BEGIN migration: 20260909090400_ops_seed_catalog.sql
-- =====================================================================
-- =====================================================================
-- LRA Ops :: seed the task catalog — DRAFT, unpriced, by design
--
-- ~15 real brokerage/sales/logistics/admin/management types, grounded in
-- what LRA actually does (PLAN.md §7 Phase 3 step 2). Every
-- `guideline_note` starts `DRAFT —` and `default_points` is NULL for
-- every row: ranking the value of LRA's own work is the founder's
-- judgement about his own business, and an agent proposing numbers would
-- launder a guess into company policy (OPEN-QUESTIONS.md #3). The
-- founder pricing this catalog is a Phase 6 gate, not built in this
-- phase.
--
-- Six of the fifteen are recurring (a matching `ops.recurring_templates`
-- row, keyed on `core.position`, follows each). Adding a position later
-- is `alter type core.position add value 'x'` plus one INSERT here — no
-- code change, per Chan's ask that this stay additive.
-- =====================================================================

insert into ops.task_types (name, category, guideline_note, is_recurring) values
  -- Brokerage
  ('Prepare and file import entry', 'Brokerage',
   'DRAFT — filing a complete, accurate import entry with BOC for one shipment. Founder to price against how much revenue/risk one entry represents.',
   false),
  ('BOC clearance follow-up', 'Brokerage',
   'DRAFT — actively chasing a submitted entry through Bureau of Customs clearance until release. Founder to price relative to filing itself.',
   false),
  ('Tariff classification for a new commodity', 'Brokerage',
   'DRAFT — researching and assigning the correct HS code for a commodity LRA has not classified before. Founder to weigh the compliance risk of getting this wrong.',
   false),
  ('Resolve a hold or discrepancy', 'Brokerage',
   'DRAFT — clearing a BOC hold, alert or documentary discrepancy that is stopping a shipment''s release. Founder to price against how disruptive an unresolved hold is.',
   false),
  ('Daily shipment status update to clients', 'Brokerage',
   'DRAFT — the recurring daily status message to clients with active shipments. Founder to price as routine/maintenance work.',
   true),

  -- Sales
  ('Quotation turnaround within SLA', 'Sales',
   'DRAFT — producing and sending a quotation to a prospect within the company''s target turnaround time. Founder to price against how often a slow quote loses the deal.',
   false),
  ('Convert a website "Free Quotation" lead', 'Sales',
   'DRAFT — following an inbound web lead through to a sent quotation. Founder to price relative to a cold-outreach quote.',
   false),
  ('Client follow-up', 'Sales',
   'DRAFT — the recurring check-in with an existing client to keep the relationship warm. Founder to price as routine/maintenance work.',
   true),
  ('Land a new account', 'Sales',
   'DRAFT — closing a genuinely new client account, not a repeat shipment from an existing one. Founder to price this as the highest-value sales outcome it is.',
   false),

  -- Logistics
  ('Arrange trucking for a released shipment', 'Logistics',
   'DRAFT — booking and confirming trucking for a shipment that has cleared BOC. Founder to price against how time-sensitive release-to-pickup is.',
   false),
  ('Warehousing coordination', 'Logistics',
   'DRAFT — coordinating storage for a shipment awaiting further processing or pickup. Founder to price against typical dwell-time risk.',
   false),

  -- Admin
  ('Statutory/accreditation filing', 'Admin',
   'DRAFT — the recurring filing that keeps LRA''s brokerage accreditation and statutory obligations current. Founder to price against the cost of lapsing.',
   true),
  ('Weekly billing and collection', 'Admin',
   'DRAFT — the recurring weekly billing run and collections follow-up. Founder to price as routine/maintenance work.',
   true),

  -- Management
  ('Run the Monday briefing', 'Management',
   'DRAFT — preparing and running the week''s briefing meeting end to end. Founder to price against how much the whole system depends on this happening well.',
   true),
  ('Clear the approval queue within 24h', 'Management',
   'DRAFT — GM/founder keeping the verification/approval queue from going stale. Founder to price against the cost of a slow approver, which PRD §3.5 already names as a real problem.',
   true);

-- ---------------------------------------------------------------------
-- Recurring templates — one per recurring type, keyed on the position
-- that owns it. `ops.generate_recurring_tasks()` (Phase 5) reads these
-- and the live `core.position` membership list; it does not switch on a
-- hardcoded position, so a sixteenth position added later needs only a
-- new template row here, never a code change.
-- ---------------------------------------------------------------------
insert into ops.recurring_templates (position, task_type_id, title, description)
select 'broker', id, 'Daily shipment status update to clients',
  'Send today''s status update to every client with an active shipment.'
from ops.task_types where name = 'Daily shipment status update to clients';

insert into ops.recurring_templates (position, task_type_id, title, description)
select 'sales', id, 'Client follow-up round',
  'Check in with existing clients this week.'
from ops.task_types where name = 'Client follow-up';

insert into ops.recurring_templates (position, task_type_id, title, description)
select 'accounting', id, 'Statutory/accreditation filing',
  'Confirm this week''s statutory and accreditation filings are current.'
from ops.task_types where name = 'Statutory/accreditation filing';

insert into ops.recurring_templates (position, task_type_id, title, description)
select 'accounting', id, 'Weekly billing and collection run',
  'Run this week''s billing and follow up on outstanding collections.'
from ops.task_types where name = 'Weekly billing and collection';

insert into ops.recurring_templates (position, task_type_id, title, description)
select 'gm', id, 'Run the Monday briefing',
  'Prepare and run this week''s Monday briefing.'
from ops.task_types where name = 'Run the Monday briefing';

insert into ops.recurring_templates (position, task_type_id, title, description)
select 'founder', id, 'Clear the approval queue',
  'Keep the verification/approval queue from going stale this week.'
from ops.task_types where name = 'Clear the approval queue within 24h';

-- END migration: 20260909090400_ops_seed_catalog.sql

-- BEGIN migration: 20260909100000_ops_ledger.sql
-- =====================================================================
-- =====================================================================
-- LRA Ops :: the points ledger — "money waiting to clear"
--
-- Append-only. One row per point-bearing transition. Balances are
-- computed from `ops.tasks`' current state, never stored or summed from
-- the ledger, because a task that bounces submitted -> rejected -> todo
-- -> submitted again writes multiple ledger rows and only the task's
-- *current* status is the true balance (PLAN.md §2.6, PRD.md §3.5).
-- =====================================================================

create type ops.ledger_state as enum ('submitted', 'verified', 'cleared', 'rejected', 'cancelled');

create table ops.point_ledger (
  id           uuid primary key default gen_random_uuid(),
  task_id      uuid not null references ops.tasks(id),
  user_id      uuid not null references core.users(id),
  week_id      uuid not null references ops.weeks(id),
  from_status  ops.task_status not null,
  to_status    ops.task_status not null,
  state        ops.ledger_state not null,
  points       int not null default 0,
  is_recurring boolean not null default false,
  is_committed boolean not null default false,
  actor_id     uuid references core.users(id),
  reason       text,
  created_at   timestamptz not null default now()
);
create index idx_ops_point_ledger_task on ops.point_ledger (task_id, created_at);
create index idx_ops_point_ledger_user_week on ops.point_ledger (user_id, week_id);

create or replace function ops.forbid_ledger_mutation()
returns trigger
language plpgsql
as $$
begin
  raise exception 'ops.point_ledger is append-only; % is not permitted', tg_op
    using errcode = '42501';
end;
$$;

create trigger trg_forbid_ledger_update
  before update on ops.point_ledger
  for each row execute function ops.forbid_ledger_mutation();

create trigger trg_forbid_ledger_delete
  before delete on ops.point_ledger
  for each row execute function ops.forbid_ledger_mutation();

alter table ops.point_ledger enable row level security;

-- Any ops member reads the whole ledger -- tasks are visible to
-- everyone by design (PRD.md §6.1) and the ledger is the receipts for
-- that same visible work.
create policy point_ledger_select on ops.point_ledger for select to authenticated
using (core.is_member('ops'));

-- No INSERT/UPDATE/DELETE policy for `authenticated`: the only path in
-- is `ops.enforce_task_transition()`, a SECURITY DEFINER trigger owned
-- by the table owner, which bypasses RLS the same way every other
-- system-only write path in this schema does.

-- ---------------------------------------------------------------------
-- Balances — computed from ops.tasks' current status, per person per
-- week. Cleared / pending-with-GM / pending-with-founder / new-vs-
-- recurring, exactly what PRD §3.5's three home-screen figures need.
-- ---------------------------------------------------------------------
create or replace view ops.v_point_balances as
select
  t.owner_user_id as user_id,
  t.week_id,
  coalesce(sum(t.points_awarded) filter (where t.status = 'cleared'), 0) as cleared_points,
  coalesce(sum(coalesce(t.points_override, t.catalog_points, 0)) filter (where t.status = 'submitted'), 0) as pending_with_gm,
  coalesce(sum(coalesce(t.points_override, t.catalog_points, 0)) filter (where t.status = 'verified'), 0) as pending_with_founder,
  coalesce(sum(coalesce(t.points_override, t.catalog_points, 0)) filter (where t.is_committed and t.status in ('todo', 'in_progress')), 0) as committed_not_submitted,
  coalesce(sum(t.points_awarded) filter (where t.status = 'cleared' and not t.is_recurring), 0) as cleared_new_points,
  coalesce(sum(t.points_awarded) filter (where t.status = 'cleared' and t.is_recurring), 0) as cleared_recurring_points,
  min(t.created_at) filter (where t.status in ('submitted', 'verified')) as oldest_pending_since
from ops.tasks t
group by t.owner_user_id, t.week_id;

comment on view ops.v_point_balances is
  'The "bank balance waiting to clear" figures for one person in one '
  'week. Computed from current task status, never from a ledger sum -- '
  'a task that bounces through rejection writes several ledger rows but '
  'has exactly one current status.';

-- ---------------------------------------------------------------------
-- Extend the transition trigger (create or replace, a NEW migration --
-- never edit an applied one) to write the ledger row and enqueue the
-- notification for every point-bearing transition. Everything from the
-- Phase 3 migration is reproduced verbatim; only the block after the
-- `case old.status` statement changes.
-- ---------------------------------------------------------------------
create or replace function ops.enforce_task_transition()
returns trigger
language plpgsql
security definer
set search_path = ops, core, public
as $$
declare
  v_owner_is_gm boolean;
  v_ledger_state ops.ledger_state;
  v_ledger_points int;
  v_ledger_reason text;
  v_recipient record;
begin
  -- 1. Unconditional bypass.
  if core.is_system_caller() or core.is_admin() then
    return new;
  end if;

  -- 2. Stamp-forgery guard, on every update whether or not status changed.
  if (new.gm_id is distinct from old.gm_id or new.gm_acted_at is distinct from old.gm_acted_at)
     and not core.is_gm() then
    raise exception 'only a GM may set gm_id/gm_acted_at' using errcode = '42501';
  end if;

  if (new.founder_id is distinct from old.founder_id
      or new.founder_acted_at is distinct from old.founder_acted_at
      or new.cleared_at is distinct from old.cleared_at
      or new.points_awarded is distinct from old.points_awarded)
     and not core.is_founder() then
    raise exception 'only a founder may set founder_id/founder_acted_at/cleared_at/points_awarded'
      using errcode = '42501';
  end if;

  if new.catalog_points is distinct from old.catalog_points then
    raise exception 'catalog_points is a server-derived snapshot and cannot be changed'
      using errcode = '42501';
  end if;

  if (new.points_override is distinct from old.points_override
      or new.points_override_reason is distinct from old.points_override_reason)
     and not core.is_oversight() then
    raise exception 'only GM/founder may set a points override' using errcode = '42501';
  end if;

  if new.points_override is not null
     and (new.points_override_reason is null or length(trim(new.points_override_reason)) < 10) then
    raise exception 'a points override requires a written reason of at least 10 characters'
      using errcode = '42501';
  end if;

  -- 3. Status unchanged -> allow (subject to the guards above), refresh activity.
  if new.status = old.status then
    new.last_activity_at := now();
    return new;
  end if;

  -- 4. Cleared is terminal.
  if old.status = 'cleared' then
    raise exception 'a cleared task is terminal and cannot be changed' using errcode = '42501';
  end if;

  if new.status = 'submitted' and new.task_type_id is null then
    raise exception 'a task must have a catalog type before it can be submitted'
      using errcode = '42501';
  end if;

  select (m.position = 'gm') into v_owner_is_gm
  from core.memberships m
  where m.user_id = new.owner_user_id and m.module = 'ops' and m.is_active
  limit 1;

  -- 5. Legal transitions.
  case old.status
    when 'todo' then
      if new.status not in ('in_progress', 'submitted', 'cancelled') then
        raise exception 'illegal transition todo -> %', new.status using errcode = '42501';
      end if;
      if new.owner_user_id <> core.auth_user_id() and not core.is_oversight() then
        raise exception 'only the owner or oversight may move this task' using errcode = '42501';
      end if;

    when 'in_progress' then
      if new.status not in ('todo', 'submitted', 'cancelled') then
        raise exception 'illegal transition in_progress -> %', new.status using errcode = '42501';
      end if;
      if new.owner_user_id <> core.auth_user_id() and not core.is_oversight() then
        raise exception 'only the owner or oversight may move this task' using errcode = '42501';
      end if;

    when 'submitted' then
      if new.status = 'verified' then
        if v_owner_is_gm then
          if not core.is_founder() then
            raise exception 'a GM cannot verify their own task; a founder must'
              using errcode = '42501';
          end if;
        else
          if not core.is_gm() then
            raise exception 'only a GM may verify a submitted task' using errcode = '42501';
          end if;
        end if;
        if new.owner_user_id = core.auth_user_id() then
          raise exception 'a task owner may not verify their own task' using errcode = '42501';
        end if;

      elsif new.status = 'rejected' then
        if not core.is_oversight() then
          raise exception 'only GM/founder may reject a task' using errcode = '42501';
        end if;
        if new.rejected_reason is null or length(trim(new.rejected_reason)) < 10 then
          raise exception 'a rejection requires a written reason of at least 10 characters'
            using errcode = '42501';
        end if;

      elsif new.status = 'in_progress' then
        if new.owner_user_id <> core.auth_user_id() and not core.is_gm() then
          raise exception 'only the owner (retracting) or a GM may return this task to in_progress'
            using errcode = '42501';
        end if;

      else
        raise exception 'illegal transition submitted -> %', new.status using errcode = '42501';
      end if;

    when 'verified' then
      if new.status = 'cleared' then
        if not core.is_clearing_founder() then
          raise exception 'only the clearing founder may clear a task' using errcode = '42501';
        end if;
        new.cleared_at := now();
        new.founder_id := core.auth_user_id();
        new.founder_acted_at := now();
        new.points_awarded := coalesce(new.points_override, new.catalog_points);

      elsif new.status = 'rejected' then
        if not core.is_founder() then
          raise exception 'only a founder may reject a verified task' using errcode = '42501';
        end if;
        if new.rejected_reason is null or length(trim(new.rejected_reason)) < 10 then
          raise exception 'a rejection requires a written reason of at least 10 characters'
            using errcode = '42501';
        end if;

      elsif new.status = 'submitted' then
        if not core.is_founder() then
          raise exception 'only a founder may send a verified task back to the GM'
            using errcode = '42501';
        end if;
        if new.rejected_reason is null or length(trim(new.rejected_reason)) < 10 then
          raise exception 'sending a task back requires a written reason of at least 10 characters'
            using errcode = '42501';
        end if;

      else
        raise exception 'illegal transition verified -> %', new.status using errcode = '42501';
      end if;

    when 'rejected' then
      if new.status <> 'todo' then
        raise exception 'illegal transition rejected -> %', new.status using errcode = '42501';
      end if;
      if new.owner_user_id <> core.auth_user_id() and not core.is_oversight() then
        raise exception 'only the owner may rework a rejected task' using errcode = '42501';
      end if;

    when 'cancelled' then
      if new.status <> 'todo' then
        raise exception 'illegal transition cancelled -> %', new.status using errcode = '42501';
      end if;
      if not core.is_oversight() then
        raise exception 'only oversight may revive a cancelled task' using errcode = '42501';
      end if;

    else
      raise exception 'unreachable status %', old.status using errcode = '42501';
  end case;

  new.last_activity_at := now();

  -- 8. Ledger + outbox — only for the five states PRD §3.5 tracks as
  -- ledger states. todo/in_progress movement writes no ledger row.
  if new.status in ('submitted', 'verified', 'cleared', 'rejected', 'cancelled') then
    v_ledger_state := new.status::text::ops.ledger_state;
    v_ledger_points := case when new.status = 'cleared' then coalesce(new.points_awarded, 0) else 0 end;
    v_ledger_reason := case
      when new.status in ('rejected') then new.rejected_reason
      when new.points_override is not null then new.points_override_reason
      else null
    end;

    insert into ops.point_ledger
      (task_id, user_id, week_id, from_status, to_status, state, points,
       is_recurring, is_committed, actor_id, reason)
    values
      (new.id, new.owner_user_id, new.week_id, old.status, new.status, v_ledger_state, v_ledger_points,
       new.is_recurring, new.is_committed, core.auth_user_id(), v_ledger_reason);

    -- Notify the party the task now sits with, or the owner on a
    -- terminal outcome. Loop rather than a single INSERT because
    -- "the GM"/"the founder" can be more than one active account.
    if new.status = 'submitted' then
      for v_recipient in
        select u.id from core.users u
        join core.memberships m on m.user_id = u.id and m.module = 'ops' and m.is_active
        where u.is_active and u.authority = 'gm'
      loop
        insert into core.notification_outbox
          (recipient_id, module, event_type, entity_type, entity_id, title, body, link)
        values
          (v_recipient.id, 'ops', 'ops.task.submitted', 'ops.task', new.id,
           'Task submitted for verification', new.title, '/queue');
      end loop;

    elsif new.status = 'verified' then
      for v_recipient in
        select u.id from core.users u
        join core.memberships m on m.user_id = u.id and m.module = 'ops' and m.is_active
        where u.is_active and u.authority = 'founder'
      loop
        insert into core.notification_outbox
          (recipient_id, module, event_type, entity_type, entity_id, title, body, link)
        values
          (v_recipient.id, 'ops', 'ops.task.verified', 'ops.task', new.id,
           'Task verified, waiting on your approval', new.title, '/queue');
      end loop;

    elsif new.status = 'cleared' then
      insert into core.notification_outbox
        (recipient_id, module, event_type, entity_type, entity_id, title, body, link)
      values
        (new.owner_user_id, 'ops', 'ops.task.cleared', 'ops.task', new.id,
         'Task cleared', format('%s points cleared for "%s"', coalesce(new.points_awarded, 0), new.title), '/points');

    elsif new.status = 'rejected' then
      insert into core.notification_outbox
        (recipient_id, module, event_type, entity_type, entity_id, title, body, link)
      values
        (new.owner_user_id, 'ops', 'ops.task.rejected', 'ops.task', new.id,
         'Task returned', coalesce(new.rejected_reason, ''), '/board');
    end if;
  end if;

  return new;
end;
$$;

-- END migration: 20260909100000_ops_ledger.sql

-- BEGIN migration: 20260909100100_ops_ledger_purge_exception.sql
-- =====================================================================
-- =====================================================================
-- LRA Ops :: a narrow, explicit exception for purging synthetic data
--
-- Chan tonight: he wants to test the whole system solo before inviting
-- the real GM/Sales/Broker/Founder, via `scripts/seed-demo.mjs --purge`
-- restoring the database to its current clean state (1 real auth user)
-- before the real invites go out.
--
-- `ops.point_ledger` is append-only "even to the service role" by the
-- same absolutism as `core.audit_logs` (PLAN.md §2.6/§0.5 lesson 7). A
-- purge of ledger rows generated entirely by throwaway `.invalid`-domain
-- demo accounts is not a rewrite of real company history, but the
-- original trigger did not distinguish the two cases at all -- it
-- refused every DELETE unconditionally.
--
-- This migration narrows, not removes, the guarantee:
--   UPDATE remains forbidden unconditionally, for every role, always --
--     a ledger row's recorded facts can never be edited, full stop.
--   DELETE is forbidden for every real business actor. It is permitted
--     ONLY for a direct system connection (`core.is_system_caller()`,
--     the same "no JWT claims" check the migrations and cron jobs use)
--     -- i.e. a service-role script run by Chan himself, never a caller
--     reachable through the API on behalf of any authenticated user.
--
-- `core.audit_logs` gets NO equivalent exception. It is the actual
-- accountability record, it has no throwaway-demo carve-out, and the
-- HR lesson it exists to fix stays absolute. Demo actors' audit rows
-- (email domain `.invalid`) are left in place by the purge script on
-- purpose -- harmless, clearly synthetic, and the guarantee that
-- nothing rewrites audit history is worth more than a perfectly empty
-- table.
--
-- Both FKs on ops.point_ledger are widened to `on delete cascade` in
-- the same migration: without it, deleting a demo task or demo user
-- would still fail with a foreign-key violation before this trigger
-- change is ever reached.
-- =====================================================================

alter table ops.point_ledger drop constraint point_ledger_task_id_fkey;
alter table ops.point_ledger
  add constraint point_ledger_task_id_fkey
  foreign key (task_id) references ops.tasks(id) on delete cascade;

alter table ops.point_ledger drop constraint point_ledger_user_id_fkey;
alter table ops.point_ledger
  add constraint point_ledger_user_id_fkey
  foreign key (user_id) references core.users(id) on delete cascade;

create or replace function ops.forbid_ledger_mutation()
returns trigger
language plpgsql
security definer
set search_path = ops, core, public
as $$
begin
  if tg_op = 'DELETE' and core.is_system_caller() then
    return old;
  end if;

  raise exception 'ops.point_ledger is append-only; % is not permitted', tg_op
    using errcode = '42501';
end;
$$;

-- END migration: 20260909100100_ops_ledger_purge_exception.sql

-- BEGIN migration: 20260909110000_ops_weeks_functions.sql
-- =====================================================================
-- =====================================================================
-- LRA Ops :: weeks — recurring generation and carry-over rollover
--
-- All three functions are `security definer`, all guarded
-- (`is_system_caller() or is_oversight()`, else 42501) and all
-- idempotent -- calling any of them twice with the same argument is a
-- no-op the second time (PLAN.md Phase 5).
--
-- The commitment LOCK trigger and the briefing screen that populates
-- `is_committed` for real are Phase 6, deliberately not built here --
-- that phase is blocked on the founder pricing the catalog. These
-- functions only move and generate tasks; they do not touch commitments.
-- =====================================================================

-- ---------------------------------------------------------------------
-- ops.generate_recurring_tasks(week_id) — one task per (active recurring
-- template, active member holding that template's position). Idempotent
-- via `uq_ops_tasks_recurring` + ON CONFLICT DO NOTHING: re-running adds
-- nothing for a member/template pair that already has a task this week.
-- ---------------------------------------------------------------------
create or replace function ops.generate_recurring_tasks(p_week_id uuid)
returns table (created_count int)
language plpgsql
security definer
set search_path = ops, core, public
as $$
declare
  v_before bigint;
  v_after bigint;
begin
  if not (core.is_system_caller() or core.is_oversight()) then
    raise exception 'only oversight may generate recurring tasks' using errcode = '42501';
  end if;

  if not exists (select 1 from ops.weeks where id = p_week_id) then
    raise exception 'unknown week %', p_week_id using errcode = 'P0002';
  end if;

  select count(*) into v_before from ops.tasks where week_id = p_week_id and is_recurring;

  insert into ops.tasks
    (week_id, owner_user_id, task_type_id, title, description, status,
     is_recurring, recurring_template_id, created_by)
  select
    p_week_id,
    m.user_id,
    rt.task_type_id,
    rt.title,
    rt.description,
    'todo',
    true,
    rt.id,
    m.user_id
  from ops.recurring_templates rt
  join core.memberships m
    on m.position = rt.position and m.module = 'ops' and m.is_active
  join core.users u on u.id = m.user_id and u.is_active
  where rt.is_active
  on conflict (owner_user_id, week_id, recurring_template_id) where recurring_template_id is not null
  do nothing;

  select count(*) into v_after from ops.tasks where week_id = p_week_id and is_recurring;

  return query select (v_after - v_before)::int;
end;
$$;

-- ---------------------------------------------------------------------
-- ops.roll_over_week(from_week_id) — every unfinished task
-- (todo/in_progress/submitted/verified/rejected) moves to the next
-- week (created in `planning` if it doesn't exist), with
-- carry_over_count incremented and first_week_id already preserved by
-- `ops.stamp_catalog_points()` at original creation. Idempotent: guarded
-- by `weeks.rolled_over_at` on the source week, so a second call is an
-- immediate no-op rather than re-matching zero rows by luck.
-- ---------------------------------------------------------------------
create or replace function ops.roll_over_week(p_from_week_id uuid)
returns table (carried_count int, next_week_id uuid)
language plpgsql
security definer
set search_path = ops, core, public
as $$
declare
  v_week ops.weeks%rowtype;
  v_next_week_start date;
  v_next_week_id uuid;
  v_carried int;
begin
  if not (core.is_system_caller() or core.is_oversight()) then
    raise exception 'only oversight may roll over a week' using errcode = '42501';
  end if;

  select * into v_week from ops.weeks where id = p_from_week_id;
  if v_week.id is null then
    raise exception 'unknown week %', p_from_week_id using errcode = 'P0002';
  end if;

  if v_week.rolled_over_at is not null then
    -- Already rolled over -- idempotent no-op. Return the existing
    -- destination so a caller retrying after a dropped response still
    -- gets a useful answer.
    select w.id into v_next_week_id from ops.weeks w where w.week_start = v_week.week_start + 7;
    return query select 0, v_next_week_id;
    return;
  end if;

  v_next_week_start := v_week.week_start + 7;

  insert into ops.weeks (week_start)
  values (v_next_week_start)
  on conflict (week_start) do nothing;

  select id into v_next_week_id from ops.weeks where week_start = v_next_week_start;

  with moved as (
    update ops.tasks
    set week_id = v_next_week_id,
        carry_over_count = carry_over_count + 1,
        last_activity_at = now()
    where week_id = p_from_week_id
      and status in ('todo', 'in_progress', 'submitted', 'verified', 'rejected')
    returning 1
  )
  select count(*) into v_carried from moved;

  update ops.weeks set rolled_over_at = now() where id = p_from_week_id;

  return query select v_carried, v_next_week_id;
end;
$$;

-- ---------------------------------------------------------------------
-- ops.close_week(week_id) — marks the week closed and rolls it over.
-- Idempotent: a week already `closed` is a no-op (rollover's own guard
-- also protects the carry-over half independently).
-- ---------------------------------------------------------------------
create or replace function ops.close_week(p_week_id uuid)
returns table (state ops.week_state, carried_count int, next_week_id uuid)
language plpgsql
security definer
set search_path = ops, core, public
as $$
declare
  v_week ops.weeks%rowtype;
  v_rollover record;
begin
  if not (core.is_system_caller() or core.is_oversight()) then
    raise exception 'only oversight may close a week' using errcode = '42501';
  end if;

  select * into v_week from ops.weeks where id = p_week_id;
  if v_week.id is null then
    raise exception 'unknown week %', p_week_id using errcode = 'P0002';
  end if;

  if v_week.state = 'closed' then
    select * into v_rollover from ops.roll_over_week(p_week_id);
    return query select v_week.state, v_rollover.carried_count, v_rollover.next_week_id;
    return;
  end if;

  update ops.weeks
  set state = 'closed', closed_at = now(), closed_by = core.auth_user_id()
  where id = p_week_id;

  select * into v_rollover from ops.roll_over_week(p_week_id);

  return query select 'closed'::ops.week_state, v_rollover.carried_count, v_rollover.next_week_id;
end;
$$;

-- END migration: 20260909110000_ops_weeks_functions.sql

